package models

type SearchResponse struct {
	Attributes []struct {
		Displayorder   int64    `json:"displayorder"`
		EsMetadataID   string   `json:"es_metadata_id"`
		ID             string   `json:"id"`
		Name           string   `json:"name"`
		Parent         bool     `json:"parent"`
		Published      int64    `json:"published"`
		ScheduleAccess []string `json:"scheduleAccess"`
		Values         []struct {
			Attribute string `json:"attribute"`
			Checked   bool   `json:"checked"`
			Child     struct {
				Displayorder   int64    `json:"displayorder"`
				ID             string   `json:"id"`
				Name           string   `json:"name"`
				Published      int64    `json:"published"`
				ScheduleAccess []string `json:"scheduleAccess"`
				Values         []struct {
					Attribute          string   `json:"attribute"`
					Displayorder       int64    `json:"displayorder"`
					ID                 string   `json:"id"`
					Name               string   `json:"name"`
					Published          int64    `json:"published"`
					RfAttributevalueID string   `json:"rf_attributevalue_id"`
					ScheduleAccess     []string `json:"scheduleAccess"`
					ViewAccess         []string `json:"viewAccess"`
					ViewAccessPublic   bool     `json:"viewAccessPublic"`
				} `json:"values"`
				ViewAccess       []string `json:"viewAccess"`
				ViewAccessPublic bool     `json:"viewAccessPublic"`
			} `json:"child"`
			Displayorder       int64    `json:"displayorder"`
			ID                 string   `json:"id"`
			Name               string   `json:"name"`
			Parent             bool     `json:"parent"`
			Published          int64    `json:"published"`
			RfAttributevalueID string   `json:"rf_attributevalue_id"`
			ScheduleAccess     []string `json:"scheduleAccess"`
			ViewAccess         []string `json:"viewAccess"`
			ViewAccessPublic   bool     `json:"viewAccessPublic"`
		} `json:"values"`
		ViewAccess       []string `json:"viewAccess"`
		ViewAccessPublic bool     `json:"viewAccessPublic"`
	} `json:"attributes"`
	ResponseCode    string `json:"responseCode"`
	ResponseMessage string `json:"responseMessage"`
	SectionList     []struct {
		From  int64 `json:"from"`
		Items []struct {
			Percentage_of_New_Content string `json:"Percentage-of-New-Content"`
			Solutions                 string `json:"Solutions"`
			Abbreviation              string `json:"abbreviation"`
			Abstract                  string `json:"abstract"`
			Attributevalues           []struct {
				Attribute          string   `json:"attribute"`
				AttributeID        string   `json:"attribute_id"`
				AttributevalueID   string   `json:"attributevalue_id"`
				Displayorder       int64    `json:"displayorder"`
				Published          int64    `json:"published"`
				RfAttributevalueID string   `json:"rf_attributevalue_id"`
				ScheduleAccess     []string `json:"scheduleAccess"`
				Value              string   `json:"value"`
				ViewAccess         []string `json:"viewAccess"`
				ViewAccessPublic   bool     `json:"viewAccessPublic"`
			} `json:"attributevalues"`
			Code      string `json:"code"`
			CodeParts struct {
				Alpha0   string `json:"alpha0"`
				Numeric1 string `json:"numeric1"`
			} `json:"codeParts"`
			CodeID        string   `json:"code_id"`
			EsMetadataID  string   `json:"es_metadata_id"`
			EventCode     string   `json:"eventCode"`
			EventID       string   `json:"eventId"`
			EventName     string   `json:"eventName"`
			FeaturedValue int64    `json:"featured_value"`
			Highlight     struct{} `json:"highlight"`
			Length        int64    `json:"length"`
			Participants  []struct {
				Speaker_Photo_Published string `json:"Speaker-Photo-Published"`
				Bio                     string `json:"bio"`
				CompanyName             string `json:"companyName"`
				Displayorder            int64  `json:"displayorder"`
				EsMetadataID            string `json:"es_metadata_id"`
				FirstName               string `json:"firstName"`
				FullName                string `json:"fullName"`
				GlobalFirstname         string `json:"globalFirstname"`
				GlobalFullName          string `json:"globalFullName"`
				GlobalJobtitle          string `json:"globalJobtitle"`
				GlobalLastname          string `json:"globalLastname"`
				GlobalPhotoURL          string `json:"globalPhotoURL"`
				JobTitle                string `json:"jobTitle"`
				LastName                string `json:"lastName"`
				PhotoURL                string `json:"photoURL"`
				Published               int64  `json:"published"`
				Roles                   string `json:"roles"`
				Session                 []struct {
					Abbreviation string `json:"abbreviation"`
					Published    string `json:"published"`
					SessionID    string `json:"sessionID"`
					SpeakerRole  string `json:"speakerRole"`
					Status       string `json:"status"`
					Times        []struct {
						Capacity           string `json:"capacity"`
						Date               string `json:"date"`
						Day                string `json:"day"`
						DayName            string `json:"dayName"`
						DaySort            string `json:"daySort"`
						DayTimeHour        string `json:"dayTimeHour"`
						DayTimeSort        string `json:"dayTimeSort"`
						EndTime            string `json:"endTime"`
						EndTimeFormatted   string `json:"endTimeFormatted"`
						EndTimeMin         int64  `json:"endTimeMin"`
						Length             int64  `json:"length"`
						LongMonth          string `json:"longMonth"`
						Room               string `json:"room"`
						SessionTimeID      string `json:"sessionTimeID"`
						ShortMonth         string `json:"shortMonth"`
						StartTime          string `json:"startTime"`
						StartTimeFormatted string `json:"startTimeFormatted"`
						StartTimeMin       int64  `json:"startTimeMin"`
						Time               string `json:"time"`
					} `json:"times"`
					Title string `json:"title"`
				} `json:"session"`
				SpeakerID string `json:"speakerId"`
				UserRef   string `json:"userRef"`
			} `json:"participants"`
			PublicViewPrivateSchedule []interface{} `json:"publicViewPrivateSchedule"`
			Published                 int64         `json:"published"`
			ScheduleAccess            []string      `json:"scheduleAccess"`
			SessionID                 string        `json:"sessionID"`
			Status                    string        `json:"status"`
			Times                     []struct {
				Capacity           string `json:"capacity"`
				Date               string `json:"date"`
				Day                string `json:"day"`
				DayName            string `json:"dayName"`
				DaySort            string `json:"daySort"`
				DayTimeHour        string `json:"dayTimeHour"`
				DayTimeSort        string `json:"dayTimeSort"`
				EndTime            string `json:"endTime"`
				EndTimeFormatted   string `json:"endTimeFormatted"`
				EndTimeMin         int64  `json:"endTimeMin"`
				Length             int64  `json:"length"`
				LongMonth          string `json:"longMonth"`
				Room               string `json:"room"`
				SessionTimeID      string `json:"sessionTimeID"`
				ShortMonth         string `json:"shortMonth"`
				StartTime          string `json:"startTime"`
				StartTimeFormatted string `json:"startTimeFormatted"`
				StartTimeMin       int64  `json:"startTimeMin"`
				Time               string `json:"time"`
			} `json:"times"`
			Title                  string   `json:"title"`
			TitleSort              string   `json:"title_sort"`
			Type                   string   `json:"type"`
			TypeDisplayorder       int64    `json:"type_displayorder"`
			TypeDisplayorderString string   `json:"type_displayorder_string"`
			UseWaitingList         string   `json:"useWaitingList"`
			ViewAccess             []string `json:"viewAccess"`
			ViewAccessPublic       bool     `json:"viewAccessPublic"`
		} `json:"items"`
		NumItems     int64  `json:"numItems"`
		SectionID    string `json:"sectionId"`
		SectionTitle string `json:"sectionTitle"`
		Size         int64  `json:"size"`
		Total        int64  `json:"total"`
	} `json:"sectionList"`
	Sections bool `json:"sections"`
}
